export interface ReportData {
    orgId: number;
    orgName: string;
    wazuhGroup: string | null;
    month: string;
    period_start: string;
    period_end: string;
    generated_at: string;
    wazuh: {
        total_alerts: number;
        critical_alerts: number;
        high_alerts: number;
        medium_alerts: number;
        top_incidents: { description: string; count: number; severity: string; agent: string }[];
        active_assets: number;
        vulnerability_count: number;
        daily_alerts: { date: string; count: number; critical: number; high: number }[];
        top_vulnerabilities: { cve: string; severity: string; cvss_score: number | null; package: string; status: string }[];
    };
    ctip: {
        total_iocs: number;
        active_campaigns: number;
        exploitable_cves: number;
    };
    postgres: {
        vendor_assessments: number;
        scans_performed: number;
        advisories_count: number;
    };
    compliance: { name: string; score: number; status: string; lastAssessed: string; nextAudit: string; color: string }[];
}

const SEV_COLOR: Record<string, string> = {
    Critical: 'bg-red-50 text-red-600 border-red-200',
    High: 'bg-orange-50 text-orange-600 border-orange-200',
    Medium: 'bg-amber-50 text-amber-600 border-amber-200',
    Low: 'bg-gray-100 text-gray-500 border-gray-200',
};

function Footer({ orgName, month }: { orgName: string; month: string }) {
    return (
        <p className="report-footer">
            Confidential — Prepared by Cybernovr Security Operations Center · For: {orgName} · Period: {month} · novrsoc-prev.vercel.app
        </p>
    );
}

function Page({ children }: { children: React.ReactNode }) {
    return <section className="report-page relative bg-white p-12 min-h-[1000px]">{children}</section>;
}

function SectionTitle({ children }: { children: React.ReactNode }) {
    return <h2 className="text-sm font-black text-slate-900 uppercase tracking-widest border-l-4 border-blue-700 pl-3 mb-6">{children}</h2>;
}

export function SecurityReportTemplate({ report }: { report: ReportData }) {
    const { wazuh, ctip, postgres, compliance } = report;

    const posture: { label: string; color: string; dot: string } =
        wazuh.critical_alerts > 0
            ? { label: 'Critical Attention Required', color: 'text-red-600', dot: 'bg-red-600' }
            : wazuh.high_alerts > 5
            ? { label: 'Elevated Risk', color: 'text-amber-600', dot: 'bg-amber-500' }
            : { label: 'Stable', color: 'text-emerald-600', dot: 'bg-emerald-500' };

    const maxDaily = Math.max(...wazuh.daily_alerts.map((d) => d.count), 1);

    const criticalOrHighVulns = wazuh.top_vulnerabilities.filter((v) => v.severity === 'Critical' || v.severity === 'High');

    const recommendations: { text: string; urgent: boolean }[] = [
        { text: 'Continue regular security awareness training', urgent: false },
        { text: 'Maintain current patch management schedule', urgent: false },
    ];
    if (wazuh.critical_alerts > 0) recommendations.push({ text: `URGENT: ${wazuh.critical_alerts} critical incident${wazuh.critical_alerts === 1 ? '' : 's'} require immediate investigation`, urgent: true });
    if (wazuh.high_alerts > 5) recommendations.push({ text: `Review and remediate ${wazuh.high_alerts} high-severity security events`, urgent: true });
    if (wazuh.vulnerability_count > 5) recommendations.push({ text: `Prioritise patching ${wazuh.vulnerability_count} identified software vulnerabilities`, urgent: true });
    if (wazuh.active_assets === 0) recommendations.push({ text: 'Deploy monitoring agents on all endpoints immediately', urgent: true });

    const generatedDate = new Date(report.generated_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    return (
        <div className="report-root bg-white text-slate-900">
            {/* Cover Page */}
            <Page>
                <div className="absolute top-0 left-0 right-0 h-2 bg-blue-700" />
                <div className="h-full flex flex-col items-center justify-center text-center gap-6">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src="/novrsoc.jpg" alt="NovrSOC" style={{ height: '48px', width: 'auto', objectFit: 'contain' }} />
                    <h1 className="text-3xl font-black text-slate-900 mt-4">Monthly Security Report</h1>
                    <div className="mt-8 space-y-2">
                        <p className="text-xl font-bold text-slate-800">{report.orgName}</p>
                        <p className="text-sm text-slate-500">Reporting Period: {report.month}</p>
                    </div>
                    <div className="mt-16 space-y-1">
                        <p className="text-xs text-slate-400">Generated by Cybernovr Security Operations Center</p>
                        <p className="text-xs text-slate-400">Date generated: {generatedDate}</p>
                    </div>
                </div>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Executive Summary */}
            <Page>
                <SectionTitle>Executive Summary</SectionTitle>
                <div className="flex items-center gap-3 mb-8">
                    <span className={`w-3 h-3 rounded-full ${posture.dot}`} />
                    <span className={`text-sm font-black ${posture.color}`}>Overall Security Posture: {posture.label}</span>
                </div>

                <div className="grid grid-cols-3 gap-4 mb-8">
                    {[
                        { label: 'Total Alerts', value: wazuh.total_alerts },
                        { label: 'Critical Alerts', value: wazuh.critical_alerts },
                        { label: 'High Alerts', value: wazuh.high_alerts },
                        { label: 'Assets Monitored', value: wazuh.active_assets },
                        { label: 'Vulnerabilities', value: wazuh.vulnerability_count },
                        { label: 'Threats Blocked (CTIP)', value: ctip.total_iocs },
                    ].map((k) => (
                        <div key={k.label} className="border border-slate-200 rounded-lg p-4">
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">{k.label}</p>
                            <p className="text-2xl font-black text-slate-900">{k.value.toLocaleString()}</p>
                        </div>
                    ))}
                </div>

                <p className="text-sm text-slate-700 leading-relaxed">
                    During {report.month}, NovrSOC monitored {wazuh.active_assets} endpoint{wazuh.active_assets === 1 ? '' : 's'} for {report.orgName}.{' '}
                    {wazuh.total_alerts.toLocaleString()} security alerts were detected, including {wazuh.critical_alerts} critical and {wazuh.high_alerts} high
                    severity events. {wazuh.vulnerability_count.toLocaleString()} vulnerabilities were identified across monitored systems. The global threat
                    intelligence feed tracked {ctip.total_iocs.toLocaleString()} malicious indicators during this period.
                </p>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Incident Summary */}
            <Page>
                <SectionTitle>Incident Summary</SectionTitle>
                <table className="w-full text-xs mb-8">
                    <thead>
                        <tr className="border-b border-slate-200">
                            {['Rank', 'Incident Type', 'Severity', 'Count', 'Affected Asset'].map((h) => (
                                <th key={h} className="text-left px-3 py-2 text-[10px] font-bold text-slate-400 uppercase tracking-wider">{h}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {wazuh.top_incidents.length === 0 ? (
                            <tr><td colSpan={5} className="px-3 py-6 text-center text-slate-400">No incidents recorded this period.</td></tr>
                        ) : (
                            wazuh.top_incidents.map((inc, i) => (
                                <tr key={i} className="border-b border-slate-100">
                                    <td className="px-3 py-2 font-bold text-slate-500">{i + 1}</td>
                                    <td className="px-3 py-2 text-slate-800">{inc.description}</td>
                                    <td className="px-3 py-2">
                                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${SEV_COLOR[inc.severity] ?? SEV_COLOR.Low}`}>{inc.severity}</span>
                                    </td>
                                    <td className="px-3 py-2 font-bold text-slate-900">{inc.count.toLocaleString()}</td>
                                    <td className="px-3 py-2 text-slate-600">{inc.agent}</td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>

                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Alert Distribution by Day</p>
                <div className="flex items-center gap-4 mb-2">
                    {[['#dc2626', 'Critical'], ['#ea580c', 'High'], ['#1d4ed8', 'Total']].map(([c, l]) => (
                        <div key={l} className="flex items-center gap-1.5">
                            <span className="w-2.5 h-2.5 rounded-sm inline-block" style={{ backgroundColor: c }} />
                            <span className="text-[9px] text-slate-500">{l}</span>
                        </div>
                    ))}
                </div>
                <div className="flex items-end gap-1.5 h-32 border-b border-slate-200 pb-1">
                    {wazuh.daily_alerts.map((d, i) => {
                        const color = d.critical > 0 ? '#dc2626' : d.high > 0 ? '#ea580c' : '#1d4ed8';
                        return (
                            <div key={i} className="flex-1 flex flex-col items-center justify-end h-full">
                                <div style={{ height: `${Math.max(2, Math.round((d.count / maxDaily) * 100))}%`, backgroundColor: color }} className="w-full rounded-t" />
                            </div>
                        );
                    })}
                </div>
                <div className="flex gap-1.5">
                    {wazuh.daily_alerts.map((d, i) => (
                        <div key={i} className="flex-1 text-center text-[8px] text-slate-400">{d.date}</div>
                    ))}
                </div>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Threat Intelligence */}
            <Page>
                <SectionTitle>Threat Intelligence</SectionTitle>
                <div className="grid grid-cols-3 gap-4 mb-8">
                    <div className="border border-slate-200 rounded-lg p-4">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">IOCs Tracked This Month</p>
                        <p className="text-2xl font-black text-slate-900">{ctip.total_iocs.toLocaleString()}</p>
                    </div>
                    <div className="border border-slate-200 rounded-lg p-4">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Active Campaigns</p>
                        <p className="text-2xl font-black text-slate-900">{ctip.active_campaigns.toLocaleString()}</p>
                    </div>
                    <div className="border border-slate-200 rounded-lg p-4">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Exploitable CVEs</p>
                        <p className="text-2xl font-black text-slate-900">{ctip.exploitable_cves.toLocaleString()}</p>
                    </div>
                </div>
                <p className="text-xs text-slate-500 italic">
                    Intelligence updated every 15 minutes from 7 global sources via Cybernovr&apos;s proprietary threat intelligence platform.
                </p>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Vulnerability Report */}
            <Page>
                <SectionTitle>Vulnerability Report</SectionTitle>
                <table className="w-full text-xs mb-6">
                    <thead>
                        <tr className="border-b border-slate-200">
                            {['CVE ID', 'Severity', 'Affected Package', 'Status'].map((h) => (
                                <th key={h} className="text-left px-3 py-2 text-[10px] font-bold text-slate-400 uppercase tracking-wider">{h}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {wazuh.top_vulnerabilities.length === 0 ? (
                            <tr><td colSpan={4} className="px-3 py-6 text-center text-slate-400">No vulnerabilities detected on monitored endpoints.</td></tr>
                        ) : (
                            wazuh.top_vulnerabilities.map((v, i) => (
                                <tr key={i} className="border-b border-slate-100">
                                    <td className="px-3 py-2 font-mono font-bold text-blue-700">{v.cve}</td>
                                    <td className="px-3 py-2">
                                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${SEV_COLOR[v.severity] ?? SEV_COLOR.Low}`}>{v.severity}</span>
                                    </td>
                                    <td className="px-3 py-2 text-slate-600">{v.package}</td>
                                    <td className="px-3 py-2 text-slate-500">{v.status}</td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>

                {criticalOrHighVulns.length > 0 && (
                    <div className="space-y-1.5">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Recommendations</p>
                        {criticalOrHighVulns.map((v, i) => (
                            <p key={i} className="text-xs text-slate-700">
                                Patch <span className="font-semibold">{v.package}</span> — {v.cve} is rated {v.severity}
                                {v.cvss_score != null ? ` (CVSS ${v.cvss_score.toFixed(1)})` : ''}.
                            </p>
                        ))}
                    </div>
                )}
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Compliance Status */}
            <Page>
                <SectionTitle>Compliance Status</SectionTitle>
                <table className="w-full text-xs mb-6">
                    <thead>
                        <tr className="border-b border-slate-200">
                            {['Framework', 'Score', 'Status', 'Last Assessed', 'Next Audit'].map((h) => (
                                <th key={h} className="text-left px-3 py-2 text-[10px] font-bold text-slate-400 uppercase tracking-wider">{h}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {compliance.map((c) => (
                            <tr key={c.name} className="border-b border-slate-100">
                                <td className="px-3 py-2 font-semibold text-slate-800">{c.name}</td>
                                <td className="px-3 py-2 font-black" style={{ color: c.color }}>{c.score}%</td>
                                <td className="px-3 py-2 text-slate-600">{c.status}</td>
                                <td className="px-3 py-2 text-slate-500">{c.lastAssessed}</td>
                                <td className="px-3 py-2 text-slate-500">{c.nextAudit}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                <p className="text-xs text-slate-700">Recommendation: Schedule quarterly compliance review.</p>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>

            {/* Recommendations */}
            <Page>
                <SectionTitle>Recommendations</SectionTitle>
                <ul className="space-y-3">
                    {recommendations.map((r, i) => (
                        <li key={i} className="flex items-start gap-3 text-sm text-slate-700">
                            <span className="flex-shrink-0">{r.urgent ? '⚠️' : '✅'}</span>
                            <span className={r.urgent ? 'font-semibold text-amber-800' : ''}>{r.text}</span>
                        </li>
                    ))}
                </ul>
                <Footer orgName={report.orgName} month={report.month} />
            </Page>
        </div>
    );
}
